// Generated by gencpp from file turtle/modeMsg.msg
// DO NOT EDIT!


#ifndef TURTLE_MESSAGE_MODEMSG_H
#define TURTLE_MESSAGE_MODEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle
{
template <class ContainerAllocator>
struct modeMsg_
{
  typedef modeMsg_<ContainerAllocator> Type;

  modeMsg_()
    : modeType()  {
    }
  modeMsg_(const ContainerAllocator& _alloc)
    : modeType(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _modeType_type;
  _modeType_type modeType;




  typedef boost::shared_ptr< ::turtle::modeMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle::modeMsg_<ContainerAllocator> const> ConstPtr;

}; // struct modeMsg_

typedef ::turtle::modeMsg_<std::allocator<void> > modeMsg;

typedef boost::shared_ptr< ::turtle::modeMsg > modeMsgPtr;
typedef boost::shared_ptr< ::turtle::modeMsg const> modeMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle::modeMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle::modeMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'turtle': ['/users/smahapat/chemo_robot_ws/src/turtle/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle::modeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle::modeMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle::modeMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle::modeMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle::modeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle::modeMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle::modeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0cc5967afa4b06a4d62ab745cf0e08b";
  }

  static const char* value(const ::turtle::modeMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0cc5967afa4b06aULL;
  static const uint64_t static_value2 = 0x4d62ab745cf0e08bULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle::modeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle/modeMsg";
  }

  static const char* value(const ::turtle::modeMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle::modeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string modeType\n\
\n\
";
  }

  static const char* value(const ::turtle::modeMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle::modeMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.modeType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct modeMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle::modeMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle::modeMsg_<ContainerAllocator>& v)
  {
    s << indent << "modeType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.modeType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_MESSAGE_MODEMSG_H
